#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Copyright 2024 Dan Higgins
# SPDX-License-Identifier: Apache-2.0

my_dotgit = File.expand_path("../.git", __dir__)
my_subdir = __dir__.split("/").last(2).join("/")

if my_subdir == "nuttall/exe" && File.directory?(my_dotgit)
  Dir.chdir("#{__dir__}/..") do
    require "bundler/setup"
  end
end

require "zeitwerk"

Zeitwerk::Loader.new.tap do |loader|
  project_dir = File.expand_path("..", __dir__)
  loader.push_dir("#{project_dir}/lib")
  loader.setup
end

exit(Nuttall::Cli.new(ARGV).run)
